version: '3'

#vars:
#  APP_VERSION: '{{.APP_VERSION|default "latest"}}'
#  sh: git log -n 1 --format=%h

vars:
  DOCKER_TAG: 
    sh: git log -n 1 --format=%h

tasks:
  pull-model:
    vars: 
      RUN_ID: '{{.RUN_ID|default "947b7b20acb24d6397b40f324a60a2ce"}}'
      MLFLOW_TRACKING_URI: '{{.MLFLOW_TRACKING_URI|default "http://localhost:5000"}}'
    cmds:
      - MLFLOW_TRACKING_URI={{.MLFLOW_TRACKING_URI}} mlflow artifacts download --artifact-uri "runs:/{{.RUN_ID}}/model"  --dst-path app/models/mlflow

  build:
    cmds:
      - docker build --build-arg DOCKER_TAG={{.DOCKER_TAG}} -t ogouni604/mlops-rakuten:{{.DOCKER_TAG}} .
      
  push:
    cmds:
      - docker push ogouni604/mlops-rakuten:{{.DOCKER_TAG}}

  deploy:
    cmds:
      - helm upgrade --install rakuten-cat-pred helm-chart -n app --create-namespace -f helm-values.yaml --set image.tag={{.DOCKER_TAG}}

  update-monitoring:
    dir: monitoring
    cmds:
      - ./update.sh

  models-2-mlflow:
    dir: scripts
    cmds:
      - python models_to_mlflow.py