version: '3'

vars:
  DOCKER_TAG: 
    sh: git log -n 1 --format=%h

tasks:
  init-flyte:
    cmds:
      - flytectl create project --id "rakuten" --description "Rakuten product category predictor" --name "Rakuten"
      
  build:
    cmds:
      - docker build -t ogouni604/mlops-rakuten-flyte:{{.DOCKER_TAG}} .

  push:
    cmds:
      - docker push ogouni604/mlops-rakuten-flyte:{{.DOCKER_TAG}}

  run:
    cmds:
      - pyflyte run --remote -p rakuten -d development --image ogouni604/mlops-rakuten-flyte:{{.DOCKER_TAG}} --envvars MLFLOW_HOST="mlflow-tracking.mlflow.svc.cluster.local:80" workflows/workflow.py ml_workflow --data_selector={{.DATA_SELECTOR}}
    vars:
      DATA_SELECTOR: '{{.DATA_SELECTOR | default ""}}'