apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-rakuten-sample-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-rakuten-sample
  template:
    metadata:
      labels:
        app: mlops-rakuten-sample
    spec:
      containers:
      - name: mlops-rakuten-sample
        image: ogouni604/mlops-rakuten
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: mlops-rakuten-sample-service
  namespace: app
  labels:
    app: mlops-rakuten-sample
spec:
  selector:
    app: mlops-rakuten-sample
  ports:
  - name: web
    port: 8000
    targetPort: 8000
  type: LoadBalancer