apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mlops-rakuten-sample-svc-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: mlops-rakuten-sample
  endpoints:
  - port: web