apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rakuten-cat-pred
  namespace: monitoring
  labels:
    release: prometheus-operator

spec:
  groups:
  - name: rakuten-cat-pred
    rules:
    - alert: RCPAccuracyDegradation
      expr: accuracy<0.75
      annotations:
        summary: "RCP accuracy < 75%"
        description: 'RCP accuracy is bellow 75%. Runbook here'
      labels:
        namespace: monitoring
        app: rakuten-cat-pred
        severity: critical
    - alert: RCPF1ScoreDegradation
      expr: f1_score<0.75
      labels:
        namespace: monitoring
        app: rakuten-cat-pred
        severity: warning
      annotations:
        summary: "RCP f1-score < 75%"
        description: 'RCP f1-score is bellow 75%. Runbook here'