apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rakuten-cat-pred
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: rakuten-cat-pred
  endpoints:
  - port: web
  targetLabels:
    - app.kubernetes.io/version